// <auto-generated />
using System;
using GreenSense.Backend.Data.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenSense.Backend.Data.Migrations
{
    [DbContext(typeof(GreenSenseDbContext))]
    partial class GreenSenseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReadingId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("NotificationId");

                    b.HasIndex("ReadingId");

                    b.HasIndex("PlantId", "CreatedAt");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlantId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PlantId");

                    b.HasIndex("UserId");

                    b.ToTable("plants", (string)null);
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SensorId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<int>("SensorType")
                        .HasColumnType("integer");

                    b.HasKey("SensorId");

                    b.HasIndex("PlantId");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.SensorReading", b =>
                {
                    b.Property<int>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReadingId"));

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("ReadingId");

                    b.HasIndex("SensorId", "MeasuredAt");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.ThresholdSettings", b =>
                {
                    b.Property<int>("ThresholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ThresholdId"));

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<double>("SoilMax")
                        .HasColumnType("double precision");

                    b.Property<double>("SoilMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TempMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TempMin")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ThresholdId");

                    b.HasIndex("PlantId")
                        .IsUnique();

                    b.ToTable("threshold_settings", (string)null);
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.Notification", b =>
                {
                    b.HasOne("GreenSense.Backend.Data.Entities.Plant", "Plant")
                        .WithMany("Notifications")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenSense.Backend.Data.Entities.SensorReading", "Reading")
                        .WithMany("Notifications")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Plant");

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.Plant", b =>
                {
                    b.HasOne("GreenSense.Backend.Data.Entities.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.Sensor", b =>
                {
                    b.HasOne("GreenSense.Backend.Data.Entities.Plant", "Plant")
                        .WithMany("Sensors")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.SensorReading", b =>
                {
                    b.HasOne("GreenSense.Backend.Data.Entities.Sensor", "Sensor")
                        .WithMany("SensorReadings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.ThresholdSettings", b =>
                {
                    b.HasOne("GreenSense.Backend.Data.Entities.Plant", "Plant")
                        .WithOne("ThresholdSettings")
                        .HasForeignKey("GreenSense.Backend.Data.Entities.ThresholdSettings", "PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.Plant", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Sensors");

                    b.Navigation("ThresholdSettings");
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.Sensor", b =>
                {
                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.SensorReading", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("GreenSense.Backend.Data.Entities.User", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
